const PostsActions = {
  FETCH_POSTS_START: "FETCH_POSTS_START",
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  FETCH_POSTS_FAILURE: "FETCH_POSTS_FAILURE",

  FETCH_POST_START: "FETCH_POST_START",
  FETCH_POST_SUCCESS: "FETCH_POST_SUCCESS",
  FETCH_POST_FAILURE: "FETCH_POST_FAILURE",
}

export default PostsActions
